import mongoose from "mongoose";
import moment from "moment";

//_id is automatically generated by MongoDB

const DataSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, ` is required` ],
  },
  surname: {
    type: String,
    required: [true, "Surname is required"],
  },
  email: {
    type: String,
    required: [true, "Email is required"],
  },
  dateOfBirth: {
    type: Date || undefined,
    required: false,
    validate: {
      validator: function (date) {
        return moment(date, "DD/MM/YYYY", true).isValid();
      },
      message: "Invalid date format, please use DD/MM/YYYY",
    },
  },
  avatar: {
    type: String,
    default: function () {
      return `https://ui-avatars.com/api/?background=random&name=${this.name}+${this.surname}`;
    },
  },
  postedOn: {
    type: Date,
    default: Date.now(),
  },
});

export default DataSchema;

/* 
_id
name
surname
email
date of birth
avatar (e.g. https://ui-avatars.com/api/?name=John+Doe, server added by using name and surname) 
*/
